name: aviation_wx
description: Dart API frontend for the NOAA Text Data Server
version: 0.0.1
authors:
- Rodney Aiglstorfer <rodney@aeyrium.com>

homepage: http://aeyrium.com

repository: https://github.com/aeyrium/aviation_wx.git

environment:
  sdk: ">=2.2.2 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  xml: ^3.3.0

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
