name: aviation_wx
description: Dart API frontend for the NOAA Text Data Server
version: 0.0.1
repository: https://github.com/aeyrium/aviation-wx.git

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  xml: ^3.3.0

dev_dependencies:
  test: ^1.6.3